# ClinicHub Deployment Configuration for Emergent Platform
# This file contains the corrected configuration for alpine-chub deployment

version: "1.0"
deployment_name: "alpine-chub"

# Frontend Configuration  
frontend:
  port: 3000
  host: "0.0.0.0"
  build_command: "yarn build"
  
  # Environment Variables for Production Build
  environment:
    REACT_APP_BACKEND_URL: "/api"
    NODE_ENV: "production"

# Backend Configuration
backend:
  port: 8001
  host: "0.0.0.0"
  health_check_path: "/api/health"
  
  # Environment Variables Required for Deployment
  environment:
    ENV: "PRODUCTION"
    HOST: "0.0.0.0"
    PORT: "8001"
    DEBUG: "false"
    
    # CORS Configuration
    FRONTEND_ORIGIN: "https://unruffled-noyce.emergent.host"

# CRITICAL: Reverse Proxy Configuration Required
# The Emergent platform MUST configure the reverse proxy to route:
# /api/* → backend:8001
# /*    → frontend:3000 (static files)

reverse_proxy:
  nginx_config: |
    server {
      server_name unruffled-noyce.emergent.host;
      listen 443 ssl http2;
      
      root /var/www/alpine-chub/build;
      index index.html;

      location /api/ {
        proxy_pass http://127.0.0.1:8001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CORS headers for API access
        add_header Access-Control-Allow-Origin https://unruffled-noyce.emergent.host always;
        add_header Access-Control-Allow-Credentials true always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization" always;
        add_header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS" always;
        if ($request_method = OPTIONS) { return 204; }
      }

      location / {
        try_files $uri /index.html;
      }
    }
    
  caddy_config: |
    unruffled-noyce.emergent.host {
      root * /var/www/alpine-chub/build
      file_server
      handle_path /api/* {
        reverse_proxy 127.0.0.1:8001
        header Access-Control-Allow-Origin "https://unruffled-noyce.emergent.host"
        header Access-Control-Allow-Credentials "true"
        header Access-Control-Allow-Headers "Content-Type, Authorization"
        header Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS"
      }
      try_files {path} /index.html
    }

# Required Secrets (must be configured in Emergent platform)
secrets:
  - name: "mongo_connection_string"
    description: "MongoDB connection string for Emergent-managed database"
    example: "mongodb://username:password@emergent-mongo:27017/clinichub"
    
  - name: "jwt_secret_key" 
    description: "JWT signing key for authentication"
    
  - name: "secret_key"
    description: "Application secret key for encryption"

# Verification Commands
verification:
  backend_direct: "curl -I http://127.0.0.1:8001/health"
  api_through_proxy: "curl -I https://unruffled-noyce.emergent.host/api/health"
  frontend: "curl -I https://unruffled-noyce.emergent.host/"

# Troubleshooting
troubleshooting:
  mixed_content_error:
    - "Ensure all API calls use relative paths (/api/endpoint)"
    - "Never use http://localhost:8001 in production builds"
    - "Configure reverse proxy to route /api/* to backend"
    
  cors_error:
    - "Verify reverse proxy is routing /api/* to backend:8001"
    - "Check CORS configuration allows https://unruffled-noyce.emergent.host"
    - "Ensure backend is binding to 0.0.0.0:8001"