services:
  # MongoDB Database with High Availability
  mongodb:
    image: mongo:6.0
    container_name: clinichub-mongodb
    restart: unless-stopped
    # SECURITY: Removed host port mapping - only accessible internally
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: clinichub
      # Enable authentication and SSL
      MONGO_REPLICA_SET_NAME: clinichub-rs
      MONGO_SSL_ENABLED: "true"
    secrets:
      - mongo_root_password
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/data/logs
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-keyfile:/data/keyfile:ro
    networks:
      - clinichub-network
    command: >
      mongod --replSet clinichub-rs 
             --bind_ip_all 
             --auth 
             --keyFile /data/keyfile
             --logpath /data/logs/mongodb.log
             --logappend
             --slowms 100
             --profile 1
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinichub-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      MONGO_URL_FILE: /run/secrets/mongo_connection_string
      SECRET_KEY_FILE: /run/secrets/app_secret_key
      JWT_SECRET_KEY_FILE: /run/secrets/jwt_secret_key
      DEBUG: "false"
      HOST: 0.0.0.0
      PORT: 8001
      DB_NAME: clinichub
    secrets:
      - mongo_connection_string
      - app_secret_key
      - jwt_secret_key
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    networks:
      - clinichub-network
    # SECURITY: Removed --reload for production
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --workers 4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinichub-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://192.168.0.243:8001
      REACT_APP_APP_NAME: ClinicHub
      REACT_APP_VERSION: 1.0.0
      GENERATE_SOURCEMAP: "false"
      DISABLE_ESLINT_PLUGIN: "true"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - clinichub-network
    command: ["sh", "-c", "yarn install && yarn start"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 45s
      timeout: 15s
      retries: 5
      start_period: 90s

volumes:
  mongodb_data:
    driver: local
  backend_logs:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  clinichub-network:
    driver: bridge

# SECURITY: Docker secrets for sensitive data
secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password
  mongo_connection_string:
    file: ./secrets/mongo_connection_string
  app_secret_key:
    file: ./secrets/app_secret_key
  jwt_secret_key:
    file: ./secrets/jwt_secret_key