services:
  mongodb:
    # simple, POSIX-shell healthcheck (no JSON arrays to confuse YAML)
    healthcheck:
      test: >
        sh -lc 'mongo --quiet --eval "db.adminCommand({ ping: 1 }).ok" | grep -q 1'
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  frontend:
    environment:
      REACT_APP_BACKEND_URL: "http://192.168.0.243:8001"
