global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # ClinicHub Backend
  - job_name: 'clinichub-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/health'
    scrape_interval: 30s

  # ClinicHub Frontend
  - job_name: 'clinichub-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  # HAPI FHIR Server
  - job_name: 'hapi-fhir'
    static_configs:
      - targets: ['hapi-fhir:8080']
    metrics_path: '/fhir/metadata'
    scrape_interval: 60s

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  # Wazuh Manager
  - job_name: 'wazuh'
    static_configs:
      - targets: ['wazuh-manager:55000']
    metrics_path: '/manager/info'
    scrape_interval: 60s