version: '3.8'

# ClinicHub Communication Infrastructure
# Phase 2B: Self-hosted Email, Fax, and VoIP Services
# Designed for Synology NAS deployment with ClinicHub integration

services:
  # Redis for Mailu
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - clinichub_communication
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Mailu - Self-hosted Email Server
  mailu_front:
    image: mailu/nginx:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    ports:
      - "25:25"     # SMTP
      - "465:465"   # SMTPS
      - "587:587"   # Submission
      - "143:143"   # IMAP
      - "993:993"   # IMAPS
      - "110:110"   # POP3
      - "995:995"   # POP3S
      - "8080:80"   # Mailu Admin Web Interface
    volumes:
      - mailu_certs:/certs
      - mailu_overrides:/overrides
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_admin
      - mailu_imap
      - mailu_smtp
    networks:
      - clinichub_communication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailu_admin:
    image: mailu/admin:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_data:/data
      - mailu_dkim:/dkim
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
    networks:
      - clinichub_communication

  mailu_imap:
    image: mailu/dovecot:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_mail:/mail
      - mailu_overrides:/overrides
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_admin
    networks:
      - clinichub_communication

  mailu_smtp:
    image: mailu/postfix:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_mailqueue:/queue
      - mailu_overrides:/overrides
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_admin
    networks:
      - clinichub_communication

  mailu_antispam:
    image: mailu/rspamd:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_filter:/var/lib/rspamd
      - mailu_overrides:/overrides
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_admin
    networks:
      - clinichub_communication

  mailu_antivirus:
    image: mailu/clamav:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_filter:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - clinichub_communication

  mailu_webmail:
    image: mailu/roundcube:2.0
    restart: unless-stopped
    env_file: ./mailu/mailu.env
    volumes:
      - mailu_webmail:/data
      - mailu_overrides:/overrides
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_imap
    networks:
      - clinichub_communication

  # HylaFAX+ - Self-hosted Fax Server
  hylafax:
    image: dchesterton/hylafax:latest
    restart: unless-stopped
    environment:
      - FAXMASTER=admin@clinic.local
      - HFAXD_SNPP_PORT=444
      - HFAXD_PORT=4559
    ports:
      - "4559:4559"   # HylaFAX daemon
      - "4560:4560"   # HylaFAX FTP
    volumes:
      - hylafax_spool:/var/spool/hylafax
      - hylafax_config:/etc/hylafax
      - hylafax_logs:/var/log/hylafax
      - /etc/localtime:/etc/localtime:ro
    networks:
      - clinichub_communication
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "hfaxd"]
      interval: 60s
      timeout: 10s
      retries: 3

  # FreeSWITCH - Open Source VoIP Platform
  freeswitch:
    image: drachtio/freeswitch:latest
    restart: unless-stopped
    environment:
      - FREESWITCH_PASSWORD=clinichub_voip_2025
    ports:
      - "5060:5060/udp"  # SIP
      - "5060:5060/tcp"  # SIP TCP
      - "5080:5080/udp"  # SIP (alternative)
      - "8021:8021"      # Event Socket Library
      - "16384-16394:16384-16394/udp"  # RTP media ports
    volumes:
      - freeswitch_config:/usr/local/freeswitch/conf
      - freeswitch_logs:/usr/local/freeswitch/log
      - freeswitch_db:/usr/local/freeswitch/db
      - freeswitch_sounds:/usr/local/freeswitch/sounds
      - /etc/localtime:/etc/localtime:ro
    networks:
      - clinichub_communication
    healthcheck:
      test: ["CMD", "fs_cli", "-x", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ClinicHub Communication Gateway
  # This service will integrate with ClinicHub backend for unified communication
  clinichub_comm_gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CLINICHUB_API_URL=http://host.docker.internal:8001/api
      - MAILU_API_URL=http://mailu_admin:80/api/v1
      - HYLAFAX_HOST=hylafax
      - FREESWITCH_HOST=freeswitch
      - FREESWITCH_PORT=8021
      - FREESWITCH_PASSWORD=clinichub_voip_2025
    ports:
      - "8100:8100"  # Communication Gateway API
    volumes:
      - comm_gateway_logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mailu_admin
      - hylafax
      - freeswitch
    networks:
      - clinichub_communication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8100/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  # Redis
  redis_data:
    driver: local

  # Mailu Email Server
  mailu_data:
    driver: local
  mailu_mail:
    driver: local
  mailu_mailqueue:
    driver: local
  mailu_filter:
    driver: local
  mailu_dkim:
    driver: local
  mailu_certs:
    driver: local
  mailu_overrides:
    driver: local
  mailu_webmail:
    driver: local

  # HylaFAX+ Fax Server
  hylafax_spool:
    driver: local
  hylafax_config:
    driver: local
  hylafax_logs:
    driver: local

  # FreeSWITCH VoIP
  freeswitch_config:
    driver: local
  freeswitch_logs:
    driver: local
  freeswitch_db:
    driver: local
  freeswitch_sounds:
    driver: local

  # Communication Gateway
  comm_gateway_logs:
    driver: local

networks:
  clinichub_communication:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16